repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--line-length=120, --safe]
      language_version: python3.7
      files: ^(userManage/)
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      exclude: 'uManage/settings.py'
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: trailing-whitespace
      language_version: python3.7
-   repo: https://github.com/miki725/importanize
    rev: '0.7'
    hooks:
    - id: importanize
      language_version: python3.7
      args: [--verbose]
